#!/bin/bash

# This application uses web workers. By default, Google Chrome does not allow
# starting workers from a local file. Passing the --allow-file-access-from-files
# to Chrome changes this behaviour, which allows the application to run. For
# this to work, all opened Chrome windows must be closed first.
#
# See README.md at the top of the repository for detail.

`google-chrome --version > /dev/null 2>&1 && echo google-chrome || echo chromium` --allow-file-access-from-files ./dist/index.html
