name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  LOCAL_IMAGE: crittersjs
  IMAGE_FILE: crittersjs-image-${{ github.sha }}.tar.gz
  TAG: ${{ github.sha }}

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read

    outputs:
      image-id: ${{ steps.save-id.outputs.image-id }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Build container image
        run: docker build -t ${LOCAL_IMAGE}:${TAG} .

      - name: Save container image ID as output
        id: save-id
        run: echo "image-id=$(docker image ls -q --no-trunc ${LOCAL_IMAGE}:${TAG})" | tee -a "$GITHUB_OUTPUT"
      
      - name: Save container image
        run: docker save ${LOCAL_IMAGE}:${TAG} | gzip > ${IMAGE_FILE}

      - name: Upload container artifact
        uses: actions/upload-artifact@v7
        with:
          # name: If the `archive` input is `false`, the name of the file uploaded will be the artifact name
          path: ${{ env.IMAGE_FILE }}
          archive: false
          retention-days: 7
          if-no-files-found: error

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist/
          retention-days: 7
  
  push-to-ghcr:
    name: Push to GHCR (ghcr.io)

    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      contents: read
      packages: write

    environment:
      name: ghcr
      url: https://github.com/${{ github.repository }}/pkgs/container/crittersjs

    env:
      GHCR_IMAGE: ghcr.io/${{ github.repository }}
      IMAGE_ID: ${{ needs.build.outputs.image-id }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.IMAGE_FILE }}
          skip-decompress: true
      
      - name: Load container image
        run: gzip -c -d ${IMAGE_FILE} | docker load
      
      - name: Check container image ID
        run: |
          id="$(docker image ls -q --no-trunc ${LOCAL_IMAGE}:${TAG})"
          echo "Expected image ID: $IMAGE_ID"
          echo "Actual image ID:   $id"
          [ -n "$id" ] && [ "$id" = "$IMAGE_ID" ]
      
      - name: Tag container image
        run: |
          docker tag ${LOCAL_IMAGE}:${TAG} ${GHCR_IMAGE}:${TAG}
          docker tag ${LOCAL_IMAGE}:${TAG} ${GHCR_IMAGE}:latest

      - name: Login to GHCR
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{github.actor}} --password-stdin
      
      - name: Push image to GHCR
        run: |
          docker push ${GHCR_IMAGE}:${TAG}
          docker push ${GHCR_IMAGE}:latest
  
  push-to-ecr:
    name: Push to ECR (public.ecr.aws)
    
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      contents: read
      id-token: write

    environment:
      name: aws
      url: https://gallery.ecr.aws/${{ github.repository }}

    env:
      ECR_IMAGE: public.ecr.aws/${{ github.repository }}
      IMAGE_ID: ${{ needs.build.outputs.image-id }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.IMAGE_FILE }}
          skip-decompress: true

      - name: Load container image
        run: gzip -c -d ${IMAGE_FILE} | docker load
      
      - name: Check container image ID
        run: |
          id="$(docker image ls -q --no-trunc ${LOCAL_IMAGE}:${TAG})"
          echo "Expected image ID: $IMAGE_ID"
          echo "Actual image ID:   $id"
          [ -n "$id" ] && [ "$id" = "$IMAGE_ID" ]
      
      - name: Tag container image
        run: |
          docker tag ${LOCAL_IMAGE}:${TAG} ${ECR_IMAGE}:${TAG}
          docker tag ${LOCAL_IMAGE}:${TAG} ${ECR_IMAGE}:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: push-ecr-${{ github.sha }}
          # 900 (i.e. 15 minutes) is the minimum
          role-duration-seconds: 900
          # Needs to be us-east-1 for ECR public
          aws-region: us-east-1

      - name: Login to ECR (public)
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Push image to ECR
        run: |
          docker push ${ECR_IMAGE}:${TAG}
          docker push ${ECR_IMAGE}:latest

  deploy-pages:
    name: Deploy GitHub Pages

    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
