name: Container dry run

on:
  pull_request:
    branches: [ '*' ]

env:
  LOCAL_IMAGE: crittersjs
  IMAGE_FILE: crittersjs-image-${{ github.sha }}.tar.gz
  TAG: ${{ github.sha }}

jobs:
  build:
    name: Build container

    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read

    outputs:
      image-id: ${{ steps.save-id.outputs.image-id }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Build container image
        run: docker build -t ${LOCAL_IMAGE}:${TAG} .

      - name: Save container image ID as output
        id: save-id
        run: echo "image-id=$(docker image ls -q --no-trunc ${LOCAL_IMAGE}:${TAG})" | tee -a "$GITHUB_OUTPUT"
      
      - name: Save container image
        run: docker save ${LOCAL_IMAGE}:${TAG} | gzip > ${IMAGE_FILE}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: container
          path: ${{ env.IMAGE_FILE }}
          archive: false
          retention-days: 7
          if-no-files-found: error
  
  push-to-ghcr:
    name: Push to GHCR (ghcr.io)

    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      contents: read

    env:
      GHCR_IMAGE: ghcr.io/${{ github.repository }}
      IMAGE_ID: ${{ needs.build.outputs.image-id }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: container
          path: ${{ env.IMAGE_FILE }}
          skip-decompress: true
      
      - name: Load container image
        run: gzip -c -d ${IMAGE_FILE} > docker load
      
      - name: Check container image ID
        run: |
          id="$(docker image ls -q --no-trunc ${LOCAL_IMAGE}:${TAG})"
          echo "Expected image ID: $IMAGE_ID"
          echo "Actual image ID:   $id"
          [ -n "$id" ] && [ "$id" = "$IMAGE_ID" ]
      
      - name: Tag container image
        run: |
          docker tag ${LOCAL_IMAGE}:${TAG} ${GHCR_IMAGE}:${TAG}
          docker tag ${LOCAL_IMAGE}:${TAG} ${GHCR_IMAGE}:latest
  
  push-to-ecr:
    name: Push to ECR (public.ecr.aws)
    
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      contents: read

    env:
      ECR_IMAGE: public.ecr.aws/${{ github.repository }}
      IMAGE_ID: ${{ needs.build.outputs.image-id }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: container
          path: ${{ env.IMAGE_FILE }}
          skip-decompress: true

      - name: Load container image
        run: gzip -c -d ${IMAGE_FILE} > docker load
      
      - name: Check container image ID
        run: |
          id="$(docker image ls -q --no-trunc ${LOCAL_IMAGE}:${TAG})"
          echo "Expected image ID: $IMAGE_ID"
          echo "Actual image ID:   $id"
          [ -n "$id" ] && [ "$id" = "$IMAGE_ID" ]
      
      - name: Tag container image
        run: |
          docker tag ${LOCAL_IMAGE}:${TAG} ${ECR_IMAGE}:${TAG}
          docker tag ${LOCAL_IMAGE}:${TAG} ${ECR_IMAGE}:latest
